[workspace]
members = ["rust-core", "rust-uniffi", "examples/demo-cmd"]

[profile.release]
lto = true
strip = true      # Automatically strip symbols from the binary.
opt-level = "s"   # Optimize for size.
panic = "abort"
codegen-units = 1
