name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwilhe2/setup-kotlin@main
      with:
        version: 1.6.21
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          ndk;21.3.6528147
          platforms;android-32
    - uses: raftario/setup-rust-action@v1
      with: 
        rust-channel: nightly
    - name: Run build
      run: make build_android
    - name: Run tests
      run: CLASSPATH="`pwd`/rust-core/resources/jna.jar:$CLASSPATH" cargo test --package fp-mobile-uniffi uniffi_foreign_language_testcase_test_kts
