name: iOS Publishing

on:
  workflow_dispatch:
  push:
    tags: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1'
    - name: which swift
      run: which swift
    - name: Run tests
      run: cargo test --package fp-mobile-uniffi uniffi_foreign_language_testcase_test_swift
    - name: Run build
      run: make build_ios

    - name: release ios
      uses: EndBug/add-and-commit@v9.1.0
      with:
          message: 'Bump new version'
          author_name: release robot
          author_email: robot@featureprobe.com
          cwd: './sdk-ios/client-sdk-ios/'
          push: ' https://${{ secrets.IOS_RELEASE_TOKEN }}@github.com/FeatureProbe/client-sdk-ios.git '
    - name: update ios submodule
      uses: EndBug/add-and-commit@v9.1.0
      with:
          message: 'update ios submodule'
          author_name: release robot
          author_email: robot@featureprobe.com
          push: 'origin main'



