name: Android Publishing

on:
  push:
    tags: [ "*" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwilhe2/setup-kotlin@main
      with:
        version: 1.6.21
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          ndk;21.3.6528147
          platforms;android-32
    - name: Run build
      run: make build_android
    - name: Publishing
      run: cd sdk-android && ./gradlew sdk:publishReleasePublicationToClient-sdk-mobileRepository -DSIGN_KEYID=${{ secrets.SIGN_KEYID }} -DSIGN_PASSWORD=${{ secrets.SIGN_PASSWORD }} -DOSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }} -DOSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}
