name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --package feature_probe_mobile_sdk_core
